---
_extends: .github

repository:
  name: ci-tools
  description: Common tools for building TokTok repositories on GitHub Action
  topics: haskell, ci, github-actions

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - code-review/reviewable
